"""Nifty 100 names not already in the core Nifty 50 universe.

Breadth/weights stay on Nifty 50. These entries are for news linking, board
promotion, stock pages, and future alerts only.
"""

from __future__ import annotations

NIFTY100_EXTRA: dict[str, dict] = {
    "ABB": {
        "name": "ABB India",
        "sector": "CAPITAL_GOODS",
        "index": "NIFTY100",
        "strong": ["abb india", "abb ltd", "abb limited"],
        "medium": ["abb"],
        "weak": [],
        "deny": ["abbot", "abbott"],
    },
    "ADANIENSOL": {
        "name": "Adani Energy Solutions",
        "sector": "POWER",
        "index": "NIFTY100",
        "strong": ["adani energy solutions", "adani energy", "adani transmission"],
        "medium": ["adaniensol"],
        "weak": [],
    },
    "ADANIGREEN": {
        "name": "Adani Green Energy",
        "sector": "POWER",
        "index": "NIFTY100",
        "strong": ["adani green energy", "adani green"],
        "medium": ["adanigreen"],
        "weak": [],
    },
    "ADANIPOWER": {
        "name": "Adani Power",
        "sector": "POWER",
        "index": "NIFTY100",
        "strong": ["adani power", "adani power ltd"],
        "medium": ["adanipower"],
        "weak": [],
    },
    "AMBUJACEM": {
        "name": "Ambuja Cements",
        "sector": "CEMENT",
        "index": "NIFTY100",
        "strong": ["ambuja cements", "ambuja cement"],
        "medium": ["ambuja"],
        "weak": [],
    },
    "DMART": {
        "name": "Avenue Supermarts",
        "sector": "RETAIL",
        "index": "NIFTY100",
        "strong": ["avenue supermarts", "d-mart", "d mart", "dmart"],
        "medium": ["avenue"],
        "weak": [],
    },
    "BAJAJHLDNG": {
        "name": "Bajaj Holdings & Investment",
        "sector": "FINANCIALS",
        "index": "NIFTY100",
        "strong": ["bajaj holdings", "bajaj holdings & investment", "bajaj holding"],
        "medium": ["bajajhldng"],
        "weak": [],
        "deny": ["bajaj finance", "bajaj finserv", "bajaj auto"],
    },
    "BANKBARODA": {
        "name": "Bank of Baroda",
        "sector": "BANK",
        "index": "NIFTY100",
        "strong": ["bank of baroda", "bank baroda"],
        "medium": ["bob bank", "bankbaroda"],
        "weak": ["bob"],
        "deny": ["baroda bnp"],
    },
    "BOSCHLTD": {
        "name": "Bosch",
        "sector": "AUTO",
        "index": "NIFTY100",
        "strong": ["bosch ltd", "bosch limited", "bosch india"],
        "medium": ["bosch"],
        "weak": [],
    },
    "CGPOWER": {
        "name": "CG Power and Industrial Solutions",
        "sector": "CAPITAL_GOODS",
        "index": "NIFTY100",
        "strong": ["cg power", "crompton greaves power", "cg power and industrial"],
        "medium": ["cgpower"],
        "weak": [],
        "deny": ["crompton greaves consumer", "crompton consumer"],
    },
    "CANBK": {
        "name": "Canara Bank",
        "sector": "BANK",
        "index": "NIFTY100",
        "strong": ["canara bank", "canara"],
        "medium": ["canbk"],
        "weak": [],
    },
    "CHOLAFIN": {
        "name": "Cholamandalam Investment and Finance",
        "sector": "NBFC",
        "index": "NIFTY100",
        "strong": [
            "cholamandalam",
            "cholamandalam investment",
            "cholamandalam finance",
            "chola finance",
        ],
        "medium": ["cholafin", "chola"],
        "weak": [],
    },
    "CUMMINSIND": {
        "name": "Cummins India",
        "sector": "CAPITAL_GOODS",
        "index": "NIFTY100",
        "strong": ["cummins india", "cummins"],
        "medium": ["cumminsind"],
        "weak": [],
    },
    "DLF": {
        "name": "DLF",
        "sector": "REALTY",
        "index": "NIFTY100",
        "strong": ["dlf ltd", "dlf limited", "dlf india"],
        "medium": ["dlf"],
        "weak": [],
    },
    "GAIL": {
        "name": "GAIL India",
        "sector": "OIL_GAS",
        "index": "NIFTY100",
        "strong": ["gail india", "gail (india)", "gas authority of india"],
        "medium": ["gail"],
        "weak": [],
    },
    "GODREJCP": {
        "name": "Godrej Consumer Products",
        "sector": "FMCG",
        "index": "NIFTY100",
        "strong": ["godrej consumer", "godrej consumer products", "godrejcp"],
        "medium": ["godrej"],
        "weak": [],
        "deny": ["godrej properties", "godrej agrovet", "godrej industries"],
    },
    "HDFCAMC": {
        "name": "HDFC Asset Management",
        "sector": "FINANCIALS",
        "index": "NIFTY100",
        "strong": ["hdfc amc", "hdfc asset management", "hdfc mutual fund amc"],
        "medium": ["hdfcamc"],
        "weak": [],
        "deny": ["hdfc bank", "hdfc life", "hdfc ltd"],
    },
    "HAL": {
        "name": "Hindustan Aeronautics",
        "sector": "DEFENCE",
        "index": "NIFTY100",
        "strong": ["hindustan aeronautics", "hal india", "hindustan aeronautics ltd"],
        "medium": [],
        "weak": ["hal"],
        "deny": ["haldiram", "halloween"],
    },
    "HINDZINC": {
        "name": "Hindustan Zinc",
        "sector": "METALS",
        "index": "NIFTY100",
        "strong": ["hindustan zinc", "hind zinc"],
        "medium": ["hindzinc"],
        "weak": [],
    },
    "HYUNDAI": {
        "name": "Hyundai Motor India",
        "sector": "AUTO",
        "index": "NIFTY100",
        "strong": ["hyundai motor india", "hyundai india", "hyundai motors india"],
        "medium": ["hyundai"],
        "weak": [],
    },
    "INDHOTEL": {
        "name": "Indian Hotels",
        "sector": "HOTELS",
        "index": "NIFTY100",
        "strong": ["indian hotels", "indian hotels company", "taj hotels", "ihcl"],
        "medium": ["indhotel"],
        "weak": [],
    },
    "IOC": {
        "name": "Indian Oil Corporation",
        "sector": "OIL_GAS",
        "index": "NIFTY100",
        "strong": ["indian oil corporation", "indian oil", "iocl"],
        "medium": ["ioc"],
        "weak": [],
        "deny": ["international olympic"],
    },
    "IRFC": {
        "name": "Indian Railway Finance Corporation",
        "sector": "FINANCIALS",
        "index": "NIFTY100",
        "strong": ["indian railway finance", "irfc", "railway finance corporation"],
        "medium": [],
        "weak": [],
    },
    "JINDALSTEL": {
        "name": "Jindal Steel",
        "sector": "METALS",
        "index": "NIFTY100",
        "strong": ["jindal steel", "jindal steel & power", "jindal steel and power"],
        "medium": ["jindalstel", "jindal"],
        "weak": [],
        "deny": ["jindal stainless", "jindal SAW"],
    },
    "LTM": {
        "name": "LTM",
        "sector": "IT",
        "index": "NIFTY100",
        "strong": [
            "ltm ltd",
            "ltm limited",
            "ltimindtree",
            "lti mindtree",
            "l&t infotech",
            "larsen & toubro infotech",
        ],
        "medium": ["ltm", "ltim"],
        "weak": [],
        "deny": ["larsen & toubro ltd", "l&t ltd"],
    },
    "LODHA": {
        "name": "Lodha Developers",
        "sector": "REALTY",
        "index": "NIFTY100",
        "strong": ["lodha developers", "macrotech developers", "lodha"],
        "medium": [],
        "weak": [],
    },
    "MAZDOCK": {
        "name": "Mazagon Dock Shipbuilders",
        "sector": "DEFENCE",
        "index": "NIFTY100",
        "strong": ["mazagon dock", "mazagoan dock", "mazdock", "mazagon dock shipbuilders"],
        "medium": [],
        "weak": [],
    },
    "MUTHOOTFIN": {
        "name": "Muthoot Finance",
        "sector": "NBFC",
        "index": "NIFTY100",
        "strong": ["muthoot finance", "muthoot fin"],
        "medium": ["muthoot"],
        "weak": [],
    },
    "PIDILITIND": {
        "name": "Pidilite Industries",
        "sector": "CHEMICALS",
        "index": "NIFTY100",
        "strong": ["pidilite industries", "pidilite", "fevicol"],
        "medium": ["pidilitind"],
        "weak": [],
    },
    "PFC": {
        "name": "Power Finance Corporation",
        "sector": "FINANCIALS",
        "index": "NIFTY100",
        "strong": ["power finance corporation", "power finance corp", "pfc ltd"],
        "medium": ["pfc"],
        "weak": [],
    },
    "PNB": {
        "name": "Punjab National Bank",
        "sector": "BANK",
        "index": "NIFTY100",
        "strong": ["punjab national bank", "pnb bank"],
        "medium": ["pnb"],
        "weak": [],
        "deny": ["pnb housing", "pnb gilts"],
    },
    "RECLTD": {
        "name": "REC",
        "sector": "FINANCIALS",
        "index": "NIFTY100",
        "strong": ["rec ltd", "rec limited", "rural electrification corporation"],
        "medium": ["recltd"],
        "weak": ["rec"],
        "deny": ["recreation", "recruitment"],
    },
    "MOTHERSON": {
        "name": "Samvardhana Motherson",
        "sector": "AUTO",
        "index": "NIFTY100",
        "strong": [
            "samvardhana motherson",
            "motherson sumi",
            "motherson international",
            "motherson",
        ],
        "medium": [],
        "weak": [],
    },
    "SHREECEM": {
        "name": "Shree Cement",
        "sector": "CEMENT",
        "index": "NIFTY100",
        "strong": ["shree cement", "shree cements"],
        "medium": ["shreecem"],
        "weak": [],
    },
    "ENRIN": {
        "name": "Siemens Energy India",
        "sector": "CAPITAL_GOODS",
        "index": "NIFTY100",
        "strong": ["siemens energy india", "siemens energy"],
        "medium": ["enrin"],
        "weak": [],
        "deny": ["siemens ltd", "siemens limited"],
    },
    "SIEMENS": {
        "name": "Siemens",
        "sector": "CAPITAL_GOODS",
        "index": "NIFTY100",
        "strong": ["siemens ltd", "siemens limited", "siemens india"],
        "medium": ["siemens"],
        "weak": [],
        "deny": ["siemens energy"],
    },
    "SOLARINDS": {
        "name": "Solar Industries",
        "sector": "CHEMICALS",
        "index": "NIFTY100",
        "strong": ["solar industries", "solar industries india"],
        "medium": ["solarinds"],
        "weak": [],
        "deny": ["adani green", "solar power"],
    },
    "TVSMOTOR": {
        "name": "TVS Motor",
        "sector": "AUTO",
        "index": "NIFTY100",
        "strong": ["tvs motor", "tvs motors", "tvs motor company"],
        "medium": ["tvs"],
        "weak": [],
        "deny": ["tvs supply", "tvs electronics"],
    },
    "TATACAP": {
        "name": "Tata Capital",
        "sector": "NBFC",
        "index": "NIFTY100",
        "strong": ["tata capital", "tata capital ltd"],
        "medium": ["tatacap"],
        "weak": [],
        "deny": ["tata consultancy", "tata motors", "tata steel"],
    },
    "TMCV": {
        "name": "Tata Motors",
        "sector": "AUTO",
        "index": "NIFTY100",
        "strong": [
            "tata motors commercial",
            "tata motors cv",
            "tmcv",
            "tata motors ltd",
        ],
        "medium": [],
        "weak": [],
        "deny": ["tata motors passenger", "tmpv", "tata motors finance"],
    },
    "TATAPOWER": {
        "name": "Tata Power",
        "sector": "POWER",
        "index": "NIFTY100",
        "strong": ["tata power", "tata power company", "tata power co"],
        "medium": ["tatapower"],
        "weak": [],
    },
    "TORNTPHARM": {
        "name": "Torrent Pharmaceuticals",
        "sector": "PHARMA",
        "index": "NIFTY100",
        "strong": ["torrent pharmaceuticals", "torrent pharma"],
        "medium": ["torrent"],
        "weak": [],
        "deny": ["torrent power"],
    },
    "UNIONBANK": {
        "name": "Union Bank of India",
        "sector": "BANK",
        "index": "NIFTY100",
        "strong": ["union bank of india", "union bank"],
        "medium": ["unionbank"],
        "weak": [],
    },
    "UNITDSPR": {
        "name": "United Spirits",
        "sector": "FMCG",
        "index": "NIFTY100",
        "strong": ["united spirits", "diageo india", "mcdowell", "unitdspr"],
        "medium": [],
        "weak": [],
    },
    "VBL": {
        "name": "Varun Beverages",
        "sector": "FMCG",
        "index": "NIFTY100",
        "strong": ["varun beverages", "varun beverage", "pepsi india bottling"],
        "medium": ["vbl"],
        "weak": [],
    },
    "ZYDUSLIFE": {
        "name": "Zydus Lifesciences",
        "sector": "PHARMA",
        "index": "NIFTY100",
        "strong": ["zydus lifesciences", "zydus life", "cadila healthcare", "zydus"],
        "medium": ["zyduslife"],
        "weak": [],
    },
}
